export const PROFILES = [
  {
    id: 'hashes',
    ar: 'بصمات SHA-256 وSHA-512',
    en: 'SHA-256 / SHA-512',
    input: 'file',
    builtin: true,
  },
  {
    id: 'strings',
    ar: 'استخراج النصوص القابلة للطباعة',
    en: 'Printable strings',
    input: 'file',
    builtin: true,
  },
  {
    id: 'file',
    ar: 'تحديد نوع الملف',
    en: 'File type',
    input: 'file',
    bin: 'file',
    args: ['--brief', '--'],
  },
  {
    id: 'exiftool',
    ar: 'تحليل البيانات الوصفية',
    en: 'Metadata analysis',
    input: 'file',
    bin: 'exiftool',
    args: ['-json', '-G', '-n'],
  },
  {
    id: 'pdfinfo',
    ar: 'خصائص مستند PDF',
    en: 'PDF metadata',
    input: 'file',
    bin: 'pdfinfo',
    args: [],
  },
  {
    id: 'pdftotext',
    ar: 'استخراج نص PDF',
    en: 'PDF text extraction',
    input: 'file',
    bin: 'pdftotext',
    args: ['-layout'],
    suffix: ['-'],
  },
  {
    id: 'mmls',
    ar: 'جدول أقسام صورة القرص',
    en: 'Disk partition layout',
    input: 'file',
    bin: 'mmls',
    args: [],
  },
  {
    id: 'fsstat',
    ar: 'خصائص نظام الملفات',
    en: 'Filesystem metadata',
    input: 'file',
    bin: 'fsstat',
    args: [],
  },
  {
    id: 'fls',
    ar: 'سرد الملفات في صورة نظام الملفات',
    en: 'Filesystem file listing',
    input: 'file',
    bin: 'fls',
    args: ['-r', '-p'],
  },
  {
    id: 'img-stat',
    ar: 'خصائص صورة القرص',
    en: 'Disk image metadata',
    input: 'file',
    bin: 'img_stat',
    args: [],
  },
  {
    id: 'capinfos',
    ar: 'إحصاءات ملف التقاط الشبكة',
    en: 'Capture statistics',
    input: 'file',
    bin: 'capinfos',
    args: [],
  },
  {
    id: 'tshark',
    ar: 'تحليل حزم محفوظة',
    en: 'Offline packet analysis',
    input: 'file',
    bin: 'tshark',
    args: ['-n', '-c', '1000', '-T', 'json', '-r'],
  },
  {
    id: 'ssdeep',
    ar: 'البصمة التقريبية للملفات',
    en: 'Fuzzy file hash',
    input: 'file',
    bin: 'ssdeep',
    args: [],
  },
  {
    id: 'yara',
    ar: 'مطابقة قواعد YARA المعتمدة محلياً',
    en: 'Local approved YARA rules',
    input: 'file',
    bin: 'yara',
    args: ['-s', '/opt/lab/rules/default.yar'],
  },
  {
    id: 'nmap',
    ar: 'جرد منافذ TCP لهدف مصرح',
    en: 'Authorized TCP port inventory',
    input: 'target',
    bin: 'nmap',
    args: [
      '-sT',
      '-Pn',
      '-n',
      '--max-retries',
      '1',
      '--host-timeout',
      '45s',
      '-p',
      '22,80,443,8080',
      '-oX',
      '-',
    ],
    connector: 'nmap-xml',
  },
];

