import test from 'node:test';
import assert from 'node:assert/strict';
import { handleLab,sha256,MAX_FILE } from '../lib/lab-core.mjs';
import { sqliteAdapter,memoryBucket,applyMigrations } from './adapter.mjs';
const db=sqliteAdapter(),bucket=memoryBucket(),env={DB:db,EVIDENCE:bucket};
applyMigrations(db,new URL('../drizzle/',import.meta.url));
const base='http://localhost:3000';
async function request(path='',body,owner='alice',extras={}){
 const opts=body===undefined?{}:{method:'POST',headers:{'content-type':'application/json','x-lab-action':'1',origin:base},body:JSON.stringify(body)};
 const r=await handleLab(new Request(`${base}/api/lab/${path}`,{...opts,...extras}),env,owner);return {status:r.status,value:await r.json()};
}
let caseId,evidenceId,taskId;
test('unauthenticated requests are denied',async()=>{assert.equal((await request('',undefined,null)).status,401);});
test('create case persists and another owner cannot access it',async()=>{const r=await request('cases',{title:'قضية تجريبية',scope:'Synthetic owned lab only',type:'forensics'});assert.equal(r.status,201);caseId=r.value.id;assert.equal((await request()).value.cases.length,1);assert.equal((await request('',undefined,'bob')).value.cases.length,0);assert.equal((await request(`cases/${caseId}/report`,undefined,'bob')).status,404);});
test('cross-origin mutations and missing custom header are denied',async()=>{for(const headers of [{'content-type':'application/json','x-lab-action':'1',origin:'https://evil.test'},{'content-type':'application/json',origin:base}])assert.equal((await request('cases',{},'alice',{headers})).status,403);});
test('malformed JSON and SQL injection are safely handled',async()=>{assert.equal((await request('cases',{},'alice',{body:'{'})).status,400);const r=await request('cases',{title:"'); DROP TABLE cases;--",scope:'training',type:'pentest'});assert.equal(r.status,201);assert.equal((await request()).value.cases.length,2);});
test('uploaded file is hashed on server and saved exactly',async()=>{const bytes=new TextEncoder().encode('Synthetic forensic evidence — دليل تجريبي');const r=await request(`cases/${caseId}/evidence`,undefined,'alice',{method:'POST',headers:{origin:base,'x-lab-action':'1','content-type':'application/octet-stream','x-evidence-meta':encodeURIComponent(JSON.stringify({name:'evidence.txt',source:'Synthetic test',custodian:'Examiner A'}))},body:bytes});assert.equal(r.status,201);evidenceId=r.value.id;assert.equal(r.value.sha256,await sha256(bytes));const download=await handleLab(new Request(`${base}/api/lab/evidence/${evidenceId}/download`),env,'alice');assert.equal(await download.text(),new TextDecoder().decode(bytes));assert.match(download.headers.get('content-disposition'),/^attachment/);});
test('oversized and empty uploads are rejected before storage',async()=>{const headers={origin:base,'x-lab-action':'1','x-evidence-meta':encodeURIComponent(JSON.stringify({name:'large.bin',source:'Test',custodian:'A'}))};const before=bucket.data.size;assert.equal((await request(`cases/${caseId}/evidence`,undefined,'alice',{method:'POST',headers:{...headers,'content-length':String(MAX_FILE+1)},body:'a'})).status,413);assert.equal((await request(`cases/${caseId}/evidence`,undefined,'alice',{method:'POST',headers,body:''})).status,400);assert.equal(bucket.data.size,before);});
test('IDOR blocked on evidence, tasks and custody',async()=>{for(const endpoint of ['verify','custody'])assert.equal((await request(`evidence/${evidenceId}/${endpoint}`,{},'bob')).status,404);});
test('integrity verification detects tampering',async()=>{assert.equal((await request(`evidence/${evidenceId}/verify`,{})).value.match,true);const key=`alice/${evidenceId}`,original=bucket.data.get(key);bucket.data.set(key,new TextEncoder().encode('tampered'));assert.equal((await request(`evidence/${evidenceId}/verify`,{})).value.match,false);bucket.data.set(key,original);});
test('custody transition preserves history and rejects stale transfer',async()=>{assert.equal((await request(`evidence/${evidenceId}/custody`,{from:'Examiner A',to:'Examiner B',reason:'Peer review'})).status,200);assert.equal((await request(`evidence/${evidenceId}/custody`,{from:'Examiner A',to:'Examiner C',reason:'Stale'})).status,409);const items=(await request(`evidence/${evidenceId}/custody`)).value.items;assert.equal(items.length,2);assert.equal(items[1].to_name,'Examiner B');});
test('open tasks block closure; closed case blocks mutation',async()=>{taskId=(await request(`cases/${caseId}/tasks`,{title:'Review evidence',assignee:'Examiner B'})).value.id;assert.equal((await request(`tasks/${taskId}`,{status:'done'},'bob')).status,404);assert.equal((await request(`cases/${caseId}/status`,{status:'closed'})).status,409);assert.equal((await request(`tasks/${taskId}`,{status:'done'})).status,200);assert.equal((await request(`cases/${caseId}/status`,{status:'closed'})).status,200);assert.equal((await request(`cases/${caseId}/tasks`,{title:'No',assignee:'No'})).status,409);});
test('reports export in both languages with evidence hashes and custody',async()=>{const ar=(await request(`cases/${caseId}/report?lang=ar`)).value.markdown,en=(await request(`cases/${caseId}/report?lang=en`)).value.markdown;assert.match(ar,/تقرير قضية/);assert.match(en,/Case report/);assert.match(en,/Examiner B/);assert.match(en,/[0-9a-f]{64}/);});
test('audit records can be checked and detect payload tampering',async()=>{const audit=(await request('audit')).value;assert.equal(audit.intact,true);assert.ok(audit.items.length>=10);assert.ok(audit.items.every(x=>x.owner==='alice'));db.raw.prepare('UPDATE events SET payload=? WHERE id=?').run('tampered',audit.items[0].id);assert.equal((await request('audit')).value.intact,false);});
test('database batch rollback preserves atomicity',async()=>{const before=db.raw.prepare('SELECT COUNT(*) AS n FROM cases').get().n;await assert.rejects(db.batch([db.prepare('INSERT INTO cases VALUES(?,?,?,?,?,?,?)').bind('rollback','alice','t','s','forensics','open','time'),db.prepare('INSERT INTO cases VALUES(?,?,?,?,?,?,?)').bind(caseId,'alice','duplicate','s','forensics','open','time')]));assert.equal(db.raw.prepare('SELECT COUNT(*) AS n FROM cases').get().n,before);});


test('database guards close the race between validation and writes',async()=>{assert.throws(()=>db.raw.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?)').run('race','alice',caseId,'late task','A','open','now'),/LAB_CASE_CLOSED/);});
test('50 simultaneous synthetic case requests retain every record',async()=>{const start=performance.now();const jobs=Array.from({length:50},(_,i)=>request('cases',{title:`Load ${i}`,scope:'synthetic',type:'forensics'},'load-user'));const results=await Promise.all(jobs);assert.ok(results.every(r=>r.status===201));assert.equal((await request('',undefined,'load-user')).value.cases.length,50);console.log(`Synthetic 50-case batch: ${Math.round(performance.now()-start)} ms; SQLite memory adapter, not a production benchmark.`);});

test('file deposit cleans staged object when a concurrent closure rejects metadata',async()=>{const id=(await request('cases',{title:'Upload race',scope:'synthetic',type:'forensics'})).value.id;const before=bucket.data.size,originalPut=bucket.put;bucket.put=async(key,bytes)=>{await originalPut(key,bytes);db.raw.prepare('UPDATE cases SET status=? WHERE id=?').run('closed',id);};try{const r=await request(`cases/${id}/evidence`,undefined,'alice',{method:'POST',headers:{origin:base,'x-lab-action':'1','x-evidence-meta':encodeURIComponent(JSON.stringify({name:'race.txt',source:'test',custodian:'A'}))},body:'synthetic'});assert.equal(r.status,409);assert.equal(bucket.data.size,before);}finally{bucket.put=originalPut;}});
test('concurrent custody requests commit one transition',async()=>{await request(`cases/${caseId}/status`,{status:'open'});const replies=await Promise.all(['C','D'].map(to=>request(`evidence/${evidenceId}/custody`,{from:'Examiner B',to,reason:'Concurrent test'})));assert.deepEqual(replies.map(r=>r.status).sort(),[200,409]);assert.equal((await request(`evidence/${evidenceId}/custody`)).value.items.length,3);});

