import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const cases=sqliteTable('cases',{id:text('id').primaryKey(),owner:text('owner').notNull(),title:text('title').notNull(),scope:text('scope').notNull(),type:text('type').notNull(),status:text('status').notNull(),created:text('created').notNull()},t=>[index('idx_cases_owner').on(t.owner)]);
export const evidence=sqliteTable('evidence',{id:text('id').primaryKey(),owner:text('owner').notNull(),case_id:text('case_id').notNull().references(()=>cases.id),name:text('name').notNull(),source:text('source').notNull(),custodian:text('custodian').notNull(),size:integer('size').notNull(),sha256:text('sha256').notNull(),object_key:text('object_key').notNull(),created:text('created').notNull()},t=>[index('idx_evidence_owner_case').on(t.owner,t.case_id)]);
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),owner:text('owner').notNull(),case_id:text('case_id').notNull().references(()=>cases.id),title:text('title').notNull(),assignee:text('assignee').notNull(),status:text('status').notNull(),created:text('created').notNull()},t=>[index('idx_tasks_owner_case').on(t.owner,t.case_id)]);
export const custody=sqliteTable('custody',{id:text('id').primaryKey(),owner:text('owner').notNull(),evidence_id:text('evidence_id').notNull().references(()=>evidence.id),case_id:text('case_id').notNull().references(()=>cases.id),from_name:text('from_name').notNull(),to_name:text('to_name').notNull(),reason:text('reason').notNull(),time:text('time').notNull()},t=>[index('idx_custody_owner_evidence').on(t.owner,t.evidence_id),index('idx_custody_owner_case').on(t.owner,t.case_id)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),owner:text('owner').notNull(),time:text('time').notNull(),action:text('action').notNull(),entity:text('entity').notNull(),payload:text('payload').notNull(),hash:text('hash').notNull()},t=>[index('idx_events_owner_time').on(t.owner,t.time)]);
export const imports=sqliteTable('imports',{id:text('id').primaryKey(),owner:text('owner').notNull(),case_id:text('case_id').notNull().references(()=>cases.id),evidence_id:text('evidence_id').notNull().references(()=>evidence.id),connector:text('connector').notNull(),parser_version:text('parser_version').notNull(),source_sha256:text('source_sha256').notNull(),count:integer('count').notNull(),created:text('created').notNull()},t=>[uniqueIndex('uq_import_source').on(t.owner,t.case_id,t.connector,t.source_sha256)]);
export const findings=sqliteTable('findings',{id:text('id').primaryKey(),owner:text('owner').notNull(),case_id:text('case_id').notNull().references(()=>cases.id),evidence_id:text('evidence_id').references(()=>evidence.id),import_id:text('import_id').references(()=>imports.id),title:text('title').notNull(),asset:text('asset').notNull(),description:text('description').notNull(),severity:text('severity').notNull(),recommendation:text('recommendation').notNull(),status:text('status').notNull(),review_note:text('review_note').notNull().default(''),revision:integer('revision').notNull().default(1),created:text('created').notNull()},t=>[index('idx_findings_owner_case').on(t.owner,t.case_id)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),owner:text('owner').notNull(),case_id:text('case_id').notNull().references(()=>cases.id),title:text('title').notNull(),kind:text('kind').notNull(),language:text('language').notNull(),markdown:text('markdown').notNull(),sha256:text('sha256').notNull(),status:text('status').notNull(),review_note:text('review_note').notNull().default(''),reviewed_by:text('reviewed_by'),reviewed_at:text('reviewed_at'),created:text('created').notNull()},t=>[index('idx_reports_owner_case').on(t.owner,t.case_id)]);
// This empty table provides an atomic NOT NULL assertion for optimistic updates.
export const revisionGuards=sqliteTable('revision_guards',{id:text('id').notNull().primaryKey()});

